[package]
name = "scheduler-rs"
version = "0.1.0"
authors = ["Antonia Calia-Bogan <alfriadox@gmail.com>"]

[dependencies]
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"
iron = "0.6.0"
#hyper = "0.12.11"
#futures = "0.1.24"