[package]
name = "scheduler-rs"
description = ""
version = "0.0.0"
authors = ["Antonia Calia-Bogan <alfriadox@gmail.com>"]
edition = "2018"

[dependencies]
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"