[package]
name = "scheduler-rs"
description = ""
version = "0.0.0"
authors = ["Antonia Calia-Bogan <alfriadox@gmail.com>"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
#rayon = "1.0.3"
#cassowary = "^0.3.0"
#quickbacktrack = "0.5.0"
serde_json = "~1.0"